#!/bin/bash
#Generates new resolv.conf file for ELS exercises

#Check for arg number
if [ -z $1 ]; then
    echo "[-] Syntax: $0 [gen|rest] [ip]"
    exit 1
fi

#Defines default value for IP
if [ -z $2 ]; then
    echo "[-] No IP value set"
    echo "[+] Setting default value 10.100.13.37"
    ip="10.100.13.37"
fi

if ["$1" = "gen" ]; then
    echo "[+] Creating backup ..."
    
    cat /etc/resolv.conf > /etc/resolv.conf.bak
    curLoc=$(pwd)
    
    echo "[+] Backup created at $curLoc"
    
    echo "[+] Writing $2 to /etc/resolv.conf"
    
    echo "#Generated by netGen.sh" > /etc/resolv.conf
    echo "search localdomain" >> /etc/resolv.conf
    echo "nameserver $ip" >> /etc/resolv.conf
    
    echo "[+] Finished writing to /etc/resolv.conf"
    
elif ["$1" = "rest" ]; then
    echo "[+] Restoring backup..."
    
    mv /etc/resolv.conf.bak /etc/resolv.conf
    
    echo "[+] Backup restored"
else
    echo "[-] Command not recognized"
    echo "[-] Syntax: $0 [gen|rest] [ip]"
fi
