#!/bin/bash

#Variables
net=10.11.1
hostFile=./liveHosts.txt
dnsServer=./dnsServer.txt
resolv=/etc/resolv.conf
domMap=./domainNameMapping.txt

##Section 1 - Ping Sweep for live hosts

#Checking if liveHosts.txt exists
if [ -f "$hostFile" ]; then
  echo "[*] $hostFile exists, deleting $hostFile..."
  rm $hostFile
fi

#Performs ping sweep to check for live hosts
for host in $(seq 255); do
  ping -c 1 $net.$host | grep "bytes from" | cut -d " " -f 4 | cut -d ":" -f 1 | tee -a $hostFile &
done

#Wait 2 seconds for any pings not yet finished
echo "[*] Waiting 2 seconds for pingsweep to finish..."
sleep 2

#Checks to see if file exists
if [ -f "$hostFile" ]; then
  echo "[*] Live hosts stored in $hostFile\n"
fi

##Section 2 - Identify DNS Server

echo "[*] Attempting to find DNS servers"

#Port Scan for port 53 and save IP in dnsServer.txt
nmap -p 53 -iL $hostFile | grep -B 4 "open" | grep "Nmap scan" | cut -d " " -f 5 | tee -a $dnsServer

#Read DNS IP from file
read -r line < $dnsServer
dnsIP=$line

#Backup resolv.conf
if [ -f $resolv ]; then
  echo "[*] $resolv exists, creating backup..."
  cp /etc/resolv.conf /etc/resolv.conf.bak && echo "[*] Backup created at /etc/resolv.conf.bak"
fi

#Create new resolv.conf
echo "[*] Overwriting $resolv with new DNS server..."
echo "# Generated by $0" > $resolv
echo "search localdomain" >> $resolv
echo "nameserver $dnsIP" >> $resolv

echo "[*] $resolv has been overwritten"

##Section 3 - Perform ns record checks

#Check if domainNameMapping
if [ -f $domMap ]; then
  echo "[*] $domMap exists, deleting file..."
  rm $domMap
fi

echo "[*] Writing to file $domMap"
echo "[*] Retrieving domain names"

#Iterate through live hosts and retrieve domain names
while read -r line; do
  ip=$line
  domainName=$(host -t ns $ip | cut -d " " -f 5)
  echo "$ip is $domainName" >> $domMap
done < "$hostFile"
